title = "Doug's Blog"
baseurl = "https://douglascuthbertson.com"
languageCode = "en-us"
disqusShortname = "cuthbertson"
enableRobotsTXT = true
# Set Hugo built-in pagination
#Paginate = 8
canonifyURLs = true
footnoteReturnLinkContents = "↩"
enableGitInfo = true
enableEmoji = true
# I think this will ignore files in this git repository, specifically, it should
# ignore .git/, .vscode/, .obsidian/, archetypes/, assets/, static, and the
# .editorconfig file.
#ignoreFiles = ["\\.git/.*", "\\.vscode/.*", "\\.editorconfig$", "\\.obsidian/.*"]
ignoreFiles = ["\\.git/.*", "\\.vscode/.*", "\\.editorconfig$", "\\.obsidian/.*", "admin"]

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  lastmod = ['lastmod', ':git', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']
  expiryDate = ['expiryDate']

# Do NOT set lineNumbersInTable to true. It really screws up how code blocks
# are displayed when their content exceeds the available width on the page.
# You wind up with a pair of horizontal scrollbars, one for the second column
# of the table (the content to the right of the line numbers) and another for
# the whole table. Both then have to be used to see the righthand edge of the
# table's content.
#
# I've set "lineNos = false". If you want line numbers in a code block, use the
# highlight shortcode and set "linenos=inline".
[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = "true"
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    style = "monokai"
    tabWidth = 4
  # These are the defaults for the new Goldmark Markdown processor.
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true # changed from false to allow embedded D3 scripts to run.
      xHTML = false

# Uncomment below to enable syntax highlighting
#pygmentsCodefences=true
#pygmentsCodefencesGuessSyntax=true
#pygmentsUseClassic=true
#pygmentsUseClasses=true
#pygmentsOptions=noclasses
# See https://xyproto.github.io/splash/docs/all.html for more styles
#pygmentsStyle = "pygments"
#pygmentsStyle = "monokai"

# See https://feathericons.com/
# The value of pre is the icon name. I had code in nav.html to render feather
# icons in the menu using SVG and the value of `pre` defined here.
[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 100
  [[menu.nav]]
    name = "Posts"
    url = "/posts/"
    weight = 500
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 700
  [[menu.nav]]
    name = "Now"
    url = "/now/"
    weight = 800
  [[menu.nav]]
    name = "Bookmarks"
    url = "/bookmarks/"
    weight = 900
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 1000

# More details about GDPR and Hugo privacy settings are at
# https://gohugo.io/about/hugo-and-gdpr/
# These settings disable the internal templates and shortcodes.

# Hugo privacy settings that work with its internal templates
# (See https://gohugo.io/templates/internal/).
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = true
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = true
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = true
    privacyEnhanced = true

# A better RSS Feed
rssLimit = 20
[author]
  name = "Douglas Cuthbertson"
  email = "doug.cuthbertson@gmail.com"

[taxonomies]
  tag = "tags"
  2015 = "2015"
  2016 = "2016"
  2020 = "2020"
  2021 = "2021"
  2022 = "2022"
  2023 = "2023"

[permalinks]
  contact = "/:sections/:slug/"
  journal = "/:sections/:slug/"
  note = "/:sections/:slug/"
  posts = "/:year/:month/:slug/"
  project = "/:sections/:slug/"
