title = "Doug's Blog"
baseurl = "https://douglascuthbertson.com"
languageCode = "en-us"
disqusShortname = "cuthbertson"
enableRobotsTXT = true
# Set Hugo built-in pagination
#Paginate = 8
canonifyURLs = true
footnoteReturnLinkContents = "↩"
enableGitInfo = true
enableEmoji = true

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

[blackfriday]
  plainIDAnchors = true
  footnoteAnchorPrefix = "footnote"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4
  # These are the defaults for the new Goldmark Markdown processor.
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true # changed from false to allow embedded D3 scripts to run.
      xHTML = false

# Uncomment below to enable syntax highlighting
pygmentsCodefences=true
pygmentsCodefencesGuessSyntax=true
#pygmentsUseClassic=true
#pygmentsUseClasses=true
#pygmentsOptions=noclasses
# See https://xyproto.github.io/splash/docs/all.html for more styles
#pygmentsStyle = "pygments"

# See https://feathericons.com/
# The value of pre is the icon name. I had code in nav.html to render feather
# icons in the menu using SVG and the value of `pre` defined here.
[menu]
  [[menu.nav]]
    name = "Home"
    #pre = "home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "About"
    #pre = "smile"
    url = "/about/"
    weight = 2
  [[menu.nav]]
    name = "Now"
    #pre = "coffee"
    url = "/now/"
    weight = 3
  [[menu.nav]]
    name = "RSS"
    #pre = "rss"
    url = "/index.xml"
    weight = 4

# More details about GDPR and Hugo privacy settings are at
# https://gohugo.io/about/hugo-and-gdpr/
# These settings disable the internal templates and shortcodes.

# Hugo privacy settings that work with its internal templates
# (See https://gohugo.io/templates/internal/).
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = true
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = true
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = true
    privacyEnhanced = true

# A better RSS Feed
rssLimit = 20
[author]
  name = "Douglas Cuthbertson"
  email = "doug.cuthbertson@gmail.com"

[taxonomies]
  category = "categories"
  tag = "tags"
  2015 = "2015"
  2016 = "2016"
  2020 = "2020"

[permalinks]
#  post = "/:filename/"
  contact = "/:sections/:slug/"
  journal = "/:sections/:slug/"
  note = "/:sections/:slug/"
  post = "/:year/:month/:slug/"
  project = "/:sections/:slug/"
