title = "Dream Sketch Code"
baseurl = "http://douglascuthbertson.com/"
languageCode = "en-us"
disqusShortname = "cuthbertson"
enableRobotsTXT = true
# Name of Academic theme folder in `themes/`.
# theme = "academic"
theme = "vanilla"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Uncomment below to enable syntax highlighting
# pygmentsCodefences = true
# pygmentsCodefencesGuessSyntax = true
# See https://xyproto.github.io/splash/docs/all.html for more styles
# pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.nav]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Notes"
    pre = "edit"
    url = "/notes/"
    weight = 2
  [[menu.nav]]
    name = "About"
    pre = "smile"
    url = "/about/"
    weight = 3
  [[menu.nav]]
    name = "Now"
    pre = "play"
    url = "/now/"
    weight = 4
  [[menu.nav]]
    name = "RSS"
    pre = "rss"
    url = "/index.xml"
    weight = 5
