title = "Doug's Blog"
baseurl = "http://douglascuthbertson.com/"
languageCode = "en-us"
disqusShortname = "cuthbertson"
enableRobotsTXT = true
# Set Hugo built-in pagination
#Paginate = 8
canonifyURLs = true
footnoteReturnLinkContents = "↩"
enableGitInfo = true

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

[blackfriday]
  plainIDAnchors = true
  footnoteAnchorPrefix = "footnote"

# Uncomment below to enable syntax highlighting
pygmentsCodefences=true
pygmentsCodefencesGuessSyntax=true
#pygmentsUseClassic=true
#pygmentsUseClasses=true
#pygmentsOptions=noclasses
# See https://xyproto.github.io/splash/docs/all.html for more styles
#pygmentsStyle = "pygments"

[permalinks]
#  post = "/:filename/"
  css = "/:year/:month/:slug/"
  journal = "/:sections/:slug/"
  note = "/:year/:month/:slug/"
  post = "/:year/:month/:slug/"
  project = "/:year/:month/:slug/"

# See https://feathericons.com/
# The value of pre is the icon name. I had code in nav.html to render feather
# icons in the menu using SVG and the value of `pre` defined here.
[menu]
  [[menu.nav]]
    name = "Home"
    #pre = "home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "About"
    #pre = "smile"
    url = "/about/"
    weight = 2
  [[menu.nav]]
    name = "Now"
    #pre = "coffee"
    url = "/now/"
    weight = 3
  [[menu.nav]]
    name = "RSS"
    #pre = "rss"
    url = "/index.xml"
    weight = 4

# More details about GDPR and Hugo privacy settings are at
# https://gohugo.io/about/hugo-and-gdpr/
# These settings disable the internal templates and shortcodes.

# Hugo privacy settings that work with its internal templates
# (See https://gohugo.io/templates/internal/).
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = true
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = true
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = true
    privacyEnhanced = true

# A better RSS Feed
copyright = "(c) 2019 Douglas Cuthbertson. This work is licensed under a Creative Commons Attribution-ShareAlike 4.0, International License"
rssLimit = 20
[author]
  name = "Douglas Cuthbertson"
  email = "doug.cuthbertson@gmail.com"

[taxonomies]
  category = "categories"
  tag = "tags"
  2015 = "2015"
  2016 = "2016"
