baseURL = "https://douglascuthbertson.com"

languageCode = "en-us"
title = "Doug's Blog"

disqusShortname = "cuthbertson"
enableRobotsTXT = true
# Set Hugo built-in pagination
#Paginate = 8
footnoteReturnLinkContents = "↩"
enableGitInfo = true
enableEmoji = true
# I think this will ignore files in this git repository, specifically, it should
# ignore .git/, .vscode/, .obsidian/, archetypes/, assets/, static, and the
# .editorconfig file.
#ignoreFiles = ["\\.git/.*", "\\.vscode/.*", "\\.editorconfig$", "\\.obsidian/.*"]
ignoreFiles = [
    "\\.git/.*",
    "\\.vscode/.*",
    "\\.editorconfig$",
    "\\.obsidian/.*",
    "admin",
]

[params]
showActiveNav = true
description = "This is my soapbox for thoughts on programming, project planning, sketching, drawing, kempo, and any other topic that may suit my fancy."
dateFormat = "Monday Jan 2, 2006"
dateFormatExtended = "Monday Jan 2, 2006 15:04"
homeText = "Black Lives Matter"
homeLink = "https://blacklivesmatter.com/"
copyright = "(c) 2015-2024 Douglas Cuthbertson (except where indicated otherwise). The content of this work is licensed under the [Creative Commons Attribution 4.0 (CC BY 4.0), International License](https://creativecommons.org/licenses/by/4.0/), again except where indicated otherwise"
footerText = "Made with Markdown, HTML, CSS, JavaScript, joy, and perseverance. Generated by [Hugo](https://gohugo.io/)"
hideFooter = false
#featuredImage = "images/banners/gargoyle-overlooking-paris.jpg"
#featuredImageDescription = "green gargoyle overlooking Paris"
featuredImage = "images/banners/motif-number-1.jpg"
featuredImageDescription = "Motif No. 1"
featuredCopyright = "copyright © 2010 Douglas Cuthbertson"
disable_comments = true
list_limit = 50

# Uncomment to include mathjax/katex everywhere. Normally math is set in front
# matter only where it's needed.
#math = true

# Set one of these to true to enable LaTeX processing.
# Note: only mathjax works; katex isn't quite compatible with the Goldmark
# markdown processor. It needs an extension similar to the one here:
# https://github.com/litao91/goldmark-mathjax
mathjax = true
katex = false
# Enable/disable baseline.js in layouts/partials/postScript.html
baseliner = false

#dropCapsFont = "cheshire"
#dropCapsFont = "de-zs"
dropCapsFont = "goudy"
#dropCapsFont = "kanzlei"
#dropCapsFont = "yinit"
mainSections = ["posts"]
planck = "\u210E"
reduced_planck = "\u210F"

[params.author]
name = "Douglas Cuthbertson"
email = "doug.cuthbertson@gmail.com"
[params.contact]
email = 'info@example.org'
phone = '+1 202-555-1212'

[frontmatter]
date = ['date', 'publishDate', 'lastmod']
lastmod = ['lastmod', ':git', 'date', 'publishDate']
publishDate = ['publishDate', 'date']
expiryDate = ['expiryDate']

# Do NOT set lineNumbersInTable to true. It really screws up how code blocks
# are displayed when their content exceeds the available width on the page.
# You wind up with a pair of horizontal scrollbars, one for the second column
# of the table (the content to the right of the line numbers) and another for
# the whole table. Both then have to be used to see the righthand edge of the
# table's content.
#
# I've set "lineNos = false". If you want line numbers in a code block, use the
# highlight shortcode and set "linenos=inline".
[markup]
[markup.tableOfContents]
endLevel = 4
[markup.highlight]
lineNumbersInTable = false
noClasses = false
# These are the defaults for the new Goldmark Markdown processor.
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true # changed from false to allow embedded D3 scripts to run.

# Uncomment below to enable syntax highlighting
#pygmentsCodefences=true
#pygmentsCodefencesGuessSyntax=true
#pygmentsUseClassic=true
#pygmentsUseClasses=true
#pygmentsOptions=noclasses
# See https://xyproto.github.io/splash/docs/all.html for more styles
#pygmentsStyle = "pygments"
#pygmentsStyle = "monokai"

# See https://feathericons.com/
# The value of pre is the icon name. I had code in nav.html to render feather
# icons in the menu using SVG and the value of `pre` defined here.
[menu]
[[menu.nav]]
name = "Home"
url = "/"
weight = 100
[[menu.nav]]
name = "About"
url = "/about/"
weight = 200
[[menu.nav]]
name = "Now"
url = "/now/"
weight = 400
[[menu.nav]]
name = "Bookmarks"
url = "/bookmarks/"
weight = 800
[[menu.nav]]
name = "RSS"
url = "/index.xml"
weight = 1600

# More details about GDPR and Hugo privacy settings are at
# https://gohugo.io/about/hugo-and-gdpr/
# These settings disable the internal templates and shortcodes.

# Hugo privacy settings that work with its internal templates
# (See https://gohugo.io/templates/internal/).
[privacy]
[privacy.disqus]
disable = true
[privacy.instagram]
disable = true
simple = false
[privacy.twitter]
disable = true
enableDNT = false
simple = false
[privacy.vimeo]
disable = true
simple = false
[privacy.youtube]
disable = true
privacyEnhanced = true

# A better RSS Feed
rssLimit = 20

[taxonomies]
tag = "tags"
2015 = "2015"
2016 = "2016"
2020 = "2020"
2021 = "2021"
2022 = "2022"
2023 = "2023"
2024 = "2024"

[permalinks]
contact = "/:sections/:slug/"
journal = "/:sections/:slug/"
note = "/:sections/:slug/"
posts = "/:year/:month/:slug/"
project = "/:sections/:slug/"
