# Vanilla theme's paramters
includeBootstrapJs = false
showActiveNav = true
containerMaxWidth = "700px"
dateFormat = "Monday Jan 2, 2006"
homeText = "An exploration of software development"
footerText = "&copy; Douglas Cuthbertson 2015. Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)"
hideFooter = false

# Custom params
paginate = 7

[[links]]
    icon = "twitter"
    title = "Twitter"
    url = "https://twitter.com/DougCuthbertson"

[[links]]
    icon = "instagram"
    title = "Instagram"
    url = "https://www.instagram.com/dbc60/"

[[links]]
    icon = "youtube"
    title = "YouTube"
    url = "https://www.youtube.com/channel/UCjYq4zK5Pc2vxwpCWUotPxg?view_as=subscriber"

[[links]]
    icon = "github"
    title = "Github"
    url = "https://github.com/dbc60"

[[links]]
    icon = "linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/douglas-cuthbertson-0487001/"
